"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WSE = void 0;
var WSE;
(function (WSE) {
    WSE["INVALID_TOKEN"] = "invalid-token";
    WSE["ASK_CREATE_ROOM"] = "ask-create-room";
    WSE["ASK_JOIN_ROOM"] = "ask-join-room";
    WSE["USER_JOINED_ROOM_SUCCESS"] = "user-joined-room-successfully";
    WSE["USER_JOINED_ROOM"] = "user-joined-room";
    WSE["USER_LEFT_ROOM"] = "user-left-room";
    WSE["CONNECTION_SUCCESS"] = "user-connected-successfully";
    WSE["DISCONNECTION"] = "disconnect";
    WSE["USER_DISCONNECTED"] = "user-disconnected";
    WSE["USER_RECONNECTED"] = "user-reconnected";
    WSE["ASK_START_GAME"] = "ask-start-game";
    WSE["START_GAME"] = "start-game";
    WSE["ASK_PLAYER_LIST"] = "ask-player-list";
    WSE["PLAYER_LIST"] = "player-list";
    WSE["CAN_DRAW"] = "user-can-draw";
    WSE["TIME_LIMIT"] = "time-limit";
    WSE["STOP_DRAW"] = "stop-draw";
    WSE["UPLOAD_DRAWING"] = "upload-drawing";
    WSE["NEW_ARTIST"] = "new-artist";
    WSE["WORD_TO_DRAW"] = "word-to-draw";
    WSE["GUESS_WORD"] = "guess-word";
    WSE["STOP_GUESS"] = "stop-guess";
    WSE["PLAYER_SCORED"] = "player-scored";
    WSE["NEW_MESSAGE"] = "new-message";
})(WSE || (exports.WSE = WSE = {}));
//# sourceMappingURL=wse.js.map