export { default as GameView } from './GameView.vue'
export { default as LandingView } from './HomeView.vue'
export { default as LobbyView } from './LobbyView.vue'
export { default as LogginView } from './LoginView.vue'
export { default as NotFound } from './NotFound.vue'
