name: Publish and deploy to VPS

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ secrets.REPO_OWNER }}/griffon
  DB_HOST: ${{secrets.DB_HOST}}
jobs:
  push_backend:
    name: Backend image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: login
        run: |
          echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Copy yarn.lock
        run: cp ./yarn.lock ./apps/api
        
      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn
        run: corepack prepare yarn@4.6.0 --activate
      - name: Build and push
        run: |
          docker build ./apps/api/Dockerfile --build-arg DB_HOST=${{secrets.DB_HOST}} --build-arg JWT_SECRET=${{secrets.JWT_SECRET}} --build-arg PORT=${{secrets.PORT}}  --build-arg DB_PORT=${{secrets.DB_PORT}} --build-arg DB_USERNAME=${{secrets.DB_USERNAME}} --build-arg DB_PASSWORD=${{secrets.DB_PASSWORD}} --build-arg DB_NAME=${{secrets.DB_NAME}} --build-arg JWT_EXPIRATION=${{secrets.JWT_EXPIRATION}}  -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api . 
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api

  push_frontend:
    name: Frontend image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn
        run: corepack prepare yarn@4.6.0 --activate

      - name: install dependencies
        run: yarn install

      - name: build front
        run: yarn run build
        
      - name: login
        run: |
          echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
      - name: Copy package-lock.json
        run: cp ./package-lock.json ./apps/web

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: apps/web/Dockerfile
          context: apps/web
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web
  deploy:
    needs: [push_backend, push_frontend]
    name: deploy image
    runs-on: ubuntu-24.04

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker compose up -d && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
